import streamlit as st
import time
import os
import base64
from PIL import Image
import io
import json

from config import APP_TITLE
from utils.helpers import get_provider_api_key, check_provider_api_key
from models.llm import get_llm
from components.sidebar import render_sidebar
from components.floating_chat import render_floating_chat
from langchain_core.messages import HumanMessage

# Constants
SAMPLE_NOTE_NAME = "sample_patient_note.png"
SAMPLE_NOTE_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "assets",
    SAMPLE_NOTE_NAME
)

MOCK_EXTRACTED_TEXT = """
CITYFRONT HEALTHCARE CLINIC
1223 8th St. Jealton, CA 30003
(800) 333-5600
CLINICAL PROGRESS NOTE

PATIENT INFORMATION
Patient Name: John Doe
DOB: 11-12-1984
Date of Visit: October 26, 2023

CHIEF COMPLAINT
Worsening chronic lower back pain with right-sided radiculopathy.

HISTORY OF PRESENT ILLNESS
Patient is a 38-year-old male with long-standing history of chronic lower back pain. Reports increased pain intensity over the past 3 months, now radiating down the right buttock and posterior thigh to the calf. Pain described as sharp and shooting, aggravated by prolonged sitting and standing. No bowel or bladder incontinence, saddle anesthesia, or lower extremity weakness reported.

PHYSICAL EXAMINATION
Range of motion limited in lumbar flexion and extension due to pain. Positive straight leg raise test on the right at 45 degrees. Decreased sensation to pinprick along the right S1 dermatome. Normal muscle strength (5/5) in bilateral lower extremities. DTRs 2+ and symmetric.

ASSESSMENT
Chronic lumbar spondylosis with right L5-S1 radiculopathy.

PLAN
1. Referral for Lumbar Spine MRI to evaluate for disk herniation or foraminal stenosis.
2. Discussed conservative management options.
3. Trial of gabapentin 100 mg tid initiated for neuropathic pain.
4. Follow-up in 4 weeks or sooner if symptoms worsen.

Dictated by: Emily Chen, MD
Date: 10/26/2023
"""

MOCK_INSURANCE_FORM = """# PRIOR AUTHORIZATION MEDICAL NECESSITY REQUEST
**CITYFRONT HEALTHCARE INFRASTRUCTURE PLATFORM**

---

### I. PATIENT & BENEFICIARY DETAILS
*   **Patient Full Name:** John Doe
*   **Date of Birth:** 11-12-1984 (Age: 38)
*   **Member ID Number:** CF-98472-A
*   **Payer Name:** Cityfront PPO Healthcare

### II. CLINICAL PROVIDER DETAILS
*   **Requesting Physician:** Emily Chen, MD
*   **Clinic Name:** Cityfront Healthcare Clinic
*   **Physical Address:** 1223 8th St. Jealton, CA 30003
*   **Clinic Telephone:** (800) 333-5600
*   **Physician NPI:** 1982730492

### III. REQUESTED SERVICE & CLINICAL CODES
*   **Requested Service:** Lumbar Spine MRI (Without Contrast)
*   **CPT Code:** 72148
*   **Primary Diagnosis (ICD-10):** M54.16 - Radiculopathy, lumbar region
*   **Secondary Diagnosis (ICD-10):** M54.50 - Low back pain, unspecified

### IV. CLINICAL EVIDENCE FOR PRIOR AUTH REQUIREMENTS
*   **Clinical Summary:** 38-year-old male presenting with worsening chronic lower back pain radiating down the right buttock and posterior thigh to the calf. Symptoms have intensified progressively over the past 3 months.
*   **Objective Clinical Findings:** Limited lumbar range of motion in flexion and extension. Positive straight leg raise test on the right at 45 degrees. Decreased sensation to pinprick along the right S1 dermatome.
*   **Failed Conservative Treatments:**
    1.  *Conservative Therapy:* Documented history of chronic lower back pain with limited physical therapy success.
    2.  *Pharmacological Intervention:* Trial of Gabapentin 100 mg tid initiated to manage neuropathic symptoms.
*   **Clinical Necessity Statement:** Lumbar Spine MRI is requested to evaluate the exact locus of L5-S1 disk herniation or foraminal stenosis correlating directly with right-sided S1 radicular symptoms.

---
**Status:** COMPLETED & PENDING CLINICIAN SIGNATURE
**Generated By:** Autonomous Prior-Auth Agentic Pipeline (v0.1.0)
"""

def setup_page():
    """Configures Streamlit page configurations."""
    st.set_page_config(
        page_title="Prior Authorization Demo",
        page_icon="📋",
        layout="wide",
        initial_sidebar_state="expanded"
    )

def encode_image_base64(image_bytes):
    """Encodes image bytes to base64 string."""
    return base64.b64encode(image_bytes).decode("utf-8")

def draw_status_bar(step):
    """Draws a premium, visually engaging progress steps indicator."""
    steps = [
        ("📂", "1. Load"),
        ("🤖", "2. Agent Working"),
        ("👀", "3. Preview"),
        ("✅", "4. Finish")
    ]
    
    html = '<div style="display: flex; justify-content: space-between; align-items: center; margin-bottom: 25px; background: rgba(255, 255, 255, 0.05); padding: 15px; border-radius: 12px; border: 1px solid rgba(255, 255, 255, 0.1);">'
    
    for idx, (icon, name) in enumerate(steps, start=1):
        # Determine styling
        if idx == step:
            # Active step
            bg = "rgba(21, 101, 192, 0.2)"
            border = "rgba(21, 101, 192, 0.8)"
            color = "#ffffff"
        elif idx < step:
            # Completed step
            bg = "rgba(46, 125, 50, 0.2)"
            border = "rgba(46, 125, 50, 0.8)"
            color = "#81c784"
        else:
            # Future step
            bg = "rgba(255, 255, 255, 0.02)"
            border = "rgba(255, 255, 255, 0.05)"
            color = "rgba(255, 255, 255, 0.3)"
            
        html += f"""
        <div style="flex: 1; text-align: center; padding: 10px; border-radius: 8px; background: {bg}; border: 1px solid {border}; margin: 0 5px;">
            <div style="font-size: 20px;">{icon}</div>
            <div style="font-weight: bold; color: {color}; font-size: 14px;">{name}</div>
        </div>
        """
        
        # Add transition arrows
        if idx < len(steps):
            html += '<div style="color: rgba(255,255,255,0.3); font-size: 18px; font-weight: bold;">➡️</div>'
            
    html += '</div>'
    st.markdown(html, unsafe_allow_html=True)

def render_prior_auth_page():
    """Renders the Prior Authorization workflow demo page."""
    st.title("📋 Autonomous Prior Authorization Agent")
    st.markdown(
        "Demonstrating autonomous extraction of medical records and matching against policy guidelines."
    )
    
    # Render global sidebar configurations
    render_sidebar()
    
    # Initialize state management
    if "pa_step" not in st.session_state:
        st.session_state.pa_step = 1
    if "uploaded_image_bytes" not in st.session_state:
        st.session_state.uploaded_image_bytes = None
    if "extracted_text" not in st.session_state:
        st.session_state.extracted_text = ""
    if "generated_form" not in st.session_state:
        st.session_state.generated_form = ""
    if "is_sample_active" not in st.session_state:
        st.session_state.is_sample_active = False

    # Render top status bar
    draw_status_bar(st.session_state.pa_step)
    
    # Step 1: LOAD STEP
    if st.session_state.pa_step == 1:
        st.subheader("📂 Step 1: Load Clinical Note")
        
        col1, col2 = st.columns([1, 1])
        
        with col1:
            st.write("Upload a scanned patient note image or choose the sample clinical record:")
            
            # File Uploader
            uploaded_file = st.file_uploader(
                "Upload Clinical Note (PNG, JPG, JPEG)",
                type=["png", "jpg", "jpeg"],
                help="Select an image file containing patient history and clinical notes."
            )
            
            if uploaded_file is not None:
                st.session_state.uploaded_image_bytes = uploaded_file.getvalue()
                st.session_state.is_sample_active = False
                st.success("Custom patient note uploaded.")
                
            # Sample button
            if st.button("👉 Use Sample Medical Progress Note", use_container_width=True):
                if os.path.exists(SAMPLE_NOTE_PATH):
                    with open(SAMPLE_NOTE_PATH, "rb") as f:
                        st.session_state.uploaded_image_bytes = f.read()
                    st.session_state.is_sample_active = True
                    st.info("Loaded Cityfront Healthcare Clinic sample note.")
                else:
                    st.error("Sample note image was not found in assets folder.")
            
            # Action Button
            if st.session_state.uploaded_image_bytes is not None:
                st.divider()
                if st.button("🚀 Start Prior Authorization Analysis", type="primary", use_container_width=True):
                    st.session_state.pa_step = 2
                    st.rerun()
            else:
                st.info("Please upload a file or click the sample note to proceed.")
                
        with col2:
            if st.session_state.uploaded_image_bytes is not None:
                st.image(
                    st.session_state.uploaded_image_bytes, 
                    caption="Loaded Clinical Image Document", 
                    use_column_width=True
                )
            else:
                st.info("No document loaded. Select the sample note or upload an image to preview.")

    # Step 2: AGENT WORKING STEP
    elif st.session_state.pa_step == 2:
        st.subheader("🤖 Step 2: Autonomous Agent Analysis in Progress")
        
        # Outer layout
        console_placeholder = st.empty()
        
        # Processing simulation
        logs = [
            "Initializing Healthcare Pipeline Router...",
            "Checking API connectivity and routing to GPT-4o-mini...",
            "🤖 [Ingestion Agent] Scanning document for structured lines...",
            "🤖 [OCR & Clinical Parser Agent] Extracting handwritten/typed characters...",
            "🤖 [Clinical Policy Matcher Agent] Pulling MCG (Milliman) and InterQual MRI guidelines...",
            "🤖 [Validation Agent] Correlating back pain symptoms with MRI medical necessity criteria...",
            "🤖 [Form Synthesizer Agent] Filling prior authorization documentation schema...",
            "Verification and sanitization audits complete. Output ready."
        ]
        
        with console_placeholder.container():
            # Terminal-style container for high tech feeling
            st.markdown(
                """
                <div style="background-color: #0b0f19; border: 1px solid #1f2937; border-radius: 8px; padding: 20px; font-family: 'Courier New', Courier, monospace; color: #10b981; margin-bottom: 20px; box-shadow: inset 0 0 10px rgba(0,0,0,0.8);">
                    <div style="display: flex; align-items: center; border-bottom: 1px solid #1f2937; padding-bottom: 10px; margin-bottom: 15px;">
                        <span style="height: 12px; width: 12px; background-color: #ef4444; border-radius: 50%; display: inline-block; margin-right: 6px;"></span>
                        <span style="height: 12px; width: 12px; background-color: #f59e0b; border-radius: 50%; display: inline-block; margin-right: 6px;"></span>
                        <span style="height: 12px; width: 12px; background-color: #10b981; border-radius: 50%; display: inline-block; margin-right: 15px;"></span>
                        <span style="color: #9ca3af; font-size: 13px;">prior-auth-agentic-terminal ~ bash</span>
                    </div>
                    <div id="terminal-content"></div>
                </div>
                """,
                unsafe_allow_html=True
            )
            
        # We will simulate logs with dynamic text updates in a typewriter style
        html_output = ""
        provider = st.session_state.get("provider", "OpenAI (ChatGPT)")
        has_api_key = check_provider_api_key(provider)
        
        for i, log in enumerate(logs):
            time.sleep(0.8)
            html_output += f"<p style='margin: 4px 0; font-size: 14px;'>$ {log}</p>"
            
            # Update terminal representation
            console_placeholder.markdown(
                f"""
                <div style="background-color: #0b0f19; border: 1px solid #1f2937; border-radius: 8px; padding: 20px; font-family: 'Courier New', Courier, monospace; color: #10b981; margin-bottom: 20px; box-shadow: inset 0 0 10px rgba(0,0,0,0.8);">
                    <div style="display: flex; align-items: center; border-bottom: 1px solid #1f2937; padding-bottom: 10px; margin-bottom: 15px;">
                        <span style="height: 12px; width: 12px; background-color: #ef4444; border-radius: 50%; display: inline-block; margin-right: 6px;"></span>
                        <span style="height: 12px; width: 12px; background-color: #f59e0b; border-radius: 50%; display: inline-block; margin-right: 6px;"></span>
                        <span style="height: 12px; width: 12px; background-color: #10b981; border-radius: 50%; display: inline-block; margin-right: 15px;"></span>
                        <span style="color: #9ca3af; font-size: 13px;">prior-auth-agentic-terminal ~ bash</span>
                    </div>
                    <div>
                        {html_output}
                        <span style="color: #10b981; font-weight: bold; animation: blink 1s infinite;">▋</span>
                    </div>
                </div>
                """,
                unsafe_allow_html=True
            )
            
        # Real LangChain Multimodal logic execution if API key is active
        if has_api_key and st.session_state.uploaded_image_bytes is not None:
            try:
                # Instantiate multimodal ChatOpenAI
                model_name = st.session_state.get("model_name", "gpt-4o-mini")
                temperature = st.session_state.get("temperature", 0.3) # lower temperature for data extraction
                api_key = get_provider_api_key(provider)
                
                llm = get_llm(
                    model_name=model_name,
                    temperature=temperature,
                    api_key=api_key
                )
                
                base64_image = encode_image_base64(st.session_state.uploaded_image_bytes)
                
                # Setup prompt messages
                prompt_content = [
                    {"type": "text", "text": "Extract all patient info, clinic info, and clinical assessment details from the image note. Output in structured form."},
                    {
                        "type": "image_url",
                        "image_url": {"url": f"data:image/png;base64,{base64_image}"},
                    },
                ]
                
                response_text = llm.invoke([HumanMessage(content=prompt_content)]).content
                st.session_state.extracted_text = response_text
                
                # Construct form prompt
                form_prompt = f"""
                You are a prior authorization clinical reviewer. Create a fully completed clinical medical necessity form matching the patient records against MRI lumbar guidelines.
                
                Here is the extracted patient records text:
                {response_text}
                
                Construct an elegant Markdown clinical Prior Authorization Form including:
                - Patient info, visit date, DOB
                - Requesting Clinic, physician, phone, NPI
                - Procedure requested (Lumbar Spine MRI, CPT 72148)
                - Diagnostic ICD-10 codes (M54.16 - Lumbar radiculopathy)
                - Clinical proof details (symptoms duration, exams positive straight leg raise, failed conservative therapy Gabapentin, etc.)
                - Clear Medical Necessity statement.
                
                Match the layout of a standard medical necessity packet.
                """
                
                form_response = llm.invoke(form_prompt).content
                st.session_state.generated_form = form_response
                
            except Exception as e:
                # Log error in terminal view and fallback gracefully
                st.warning(f"Live API extraction encounterd error: {str(e)}. Proceeding with high-fidelity mock engine fallback.")
                st.session_state.extracted_text = MOCK_EXTRACTED_TEXT
                st.session_state.generated_form = MOCK_INSURANCE_FORM
        else:
            # Fallback mock engine (designed to deliver robust demos offline/without key)
            st.session_state.extracted_text = MOCK_EXTRACTED_TEXT
            st.session_state.generated_form = MOCK_INSURANCE_FORM
            
        time.sleep(1.0)
        st.session_state.pa_step = 3
        st.rerun()

    # Step 3: PREVIEW STEP
    elif st.session_state.pa_step == 3:
        st.subheader("👀 Step 3: Clinician Preview & Verification")
        
        col1, col2 = st.columns([1, 1.2])
        
        with col1:
            st.markdown("#### Patient Records Image Document")
            st.image(st.session_state.uploaded_image_bytes, use_column_width=True)
            
            with st.expander("📝 Extracted Raw Document Text", expanded=False):
                st.text_area("OCR Raw Output", st.session_state.extracted_text, height=300)
                
        with col2:
            st.markdown("#### Generated Medical Necessity Prior Auth Form")
            
            # Render Markdown form inside a neat container
            st.markdown(
                f"""
                <div style="background-color: rgba(255, 255, 255, 0.03); border: 1px solid rgba(255, 255, 255, 0.1); border-radius: 8px; padding: 25px; margin-bottom: 20px; font-size: 14px;">
                    {st.session_state.generated_form}
                </div>
                """,
                unsafe_allow_html=True
            )
            
            # Action buttons
            b1, b2 = st.columns(2)
            with b1:
                if st.button("⬅️ Restart / Reset", use_container_width=True):
                    st.session_state.pa_step = 1
                    st.session_state.uploaded_image_bytes = None
                    st.session_state.extracted_text = ""
                    st.session_state.generated_form = ""
                    st.rerun()
            with b2:
                if st.button("✍️ Approve & Finalize Form", type="primary", use_container_width=True):
                    st.session_state.pa_step = 4
                    st.rerun()

    # Step 4: FINISH STEP
    elif st.session_state.pa_step == 4:
        st.subheader("✅ Step 4: Completed & Document Ready")
        
        # Display completion box
        st.markdown(
            """
            <div style="background-color: rgba(46, 125, 50, 0.1); border: 1px solid rgba(46, 125, 50, 0.4); border-radius: 12px; padding: 30px; text-align: center; margin-bottom: 30px;">
                <h2 style="color: #81c784; margin-top: 0;">🎉 Prior Authorization Package Finalized</h2>
                <p style="font-size: 16px;">The multi-agent loop has extracted medical notes, verified necessity, and mapped standard insurance records.</p>
                <p style="font-size: 14px; color: rgba(255,255,255,0.7);">Ready for download and direct EHR integration.</p>
            </div>
            """,
            unsafe_allow_html=True
        )
        
        # Download Section
        form_data = st.session_state.generated_form
        
        c1, c2, c3 = st.columns([1, 2, 1])
        with c2:
            # File download button
            st.download_button(
                label="💾 Download Prior Auth Medical Necessity Form (.md)",
                data=form_data,
                file_name="Prior_Auth_Medical_Necessity_Form.md",
                mime="text/markdown",
                use_container_width=True,
                type="primary"
            )
            
            # Let's provide a JSON export option as well
            json_export = {
                "document_type": "prior_authorization_form",
                "platform": "Cityfront Healthcare Platform",
                "extracted_text": st.session_state.extracted_text,
                "completed_form_markdown": st.session_state.generated_form
            }
            
            st.download_button(
                label="⚙️ Download Raw EHR Structured Record (.json)",
                data=json.dumps(json_export, indent=4),
                file_name="Prior_Auth_Payload.json",
                mime="application/json",
                use_container_width=True
            )
            
            st.divider()
            
            if st.button("🔄 Start New Authorization Request", use_container_width=True):
                st.session_state.pa_step = 1
                st.session_state.uploaded_image_bytes = None
                st.session_state.extracted_text = ""
                st.session_state.generated_form = ""
                st.rerun()
                
    # Render Floating Chat Widget
    render_floating_chat()

if __name__ == "__main__":
    setup_page()
    render_prior_auth_page()
